---
- name: Instalar Apache y habilitar el servicio
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Asegurar que Apache está habilitado y corriendo
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: Instalar PHP y extensiones
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-common
    - php-mysql
    - php-xml
    - php-curl
    - php-gd
    - php-cli
    - php-mbstring
    - php-opcache
    - php-soap
    - php-zip
    - php-intl

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes

- name: Configurar permisos para WordPress
  file:
    path: /var/www/html/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes

- name: Configurar archivo wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Habilitar módulo de reescritura en Apache
  command: a2enmod rewrite
  notify: Reiniciar Apache

- name: Configurar Apache para WordPress
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf

- name: Habilitar VirtualHost de WordPress
  command: a2ensite wordpress.conf
  notify: Reiniciar Apache

- name: Deshabilitar sitio por defecto
  command: a2dissite 000-default.conf
  notify: Reiniciar Apache

